baseURL = 'https://xn--h-zfa.xyz/'
theme = ["hugo-theme-shell", "projektemacher-base"]
title = "Äh.XYZ"
languageCode = "en"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
paginate = 5
enableInlineShortcodes = true
copyright = "<a href=\"https://labs.projektemacher.org\">Projektemacher Labs</a>"

[languages]
  [languages.de]
    languagename = "Deutsch"

    [languages.de.params]

  [languages.en]
      languagename = "English"
      [languages.en.params]

[markup.goldmark.renderer]
  unsafe = true

[imaging]
    quality = 95

[mediaTypes]
  [mediaTypes."application/x-qrcode-template"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.qrcode]
    mediaType = "application/x-qrcode-template"
    isPlainText = true
    isHTML = false
    baseName = "qrcode"
    notAlternative = true

[sitemap]
  changeFreq = 'weekly'

[build]
  writeStats = true
