name: Publish on GitHub pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 23 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUGO_VERSION: 0.136.5

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)

      - name: Checkout submodules
        run: |
          git submodule update --init --depth 1 -j 4 themes/*
          for dir in `ls blogs/`; do echo "Checking out submodule blogs/$dir" ; git submodule update --depth 1 -j 4 --init blogs/$dir ; rm -rf blogs/$dir/.git ; find blogs/$dir -type f -size +1M -name '*.jpg' -print -exec rm {} \;  ; done
#          ./scripts/git-checkout.sh

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: '.nvmrc'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install required dependencies
        run: |
          ./scripts/github-setup.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Generate Files
        env:
          SKIP_IIIF: yes
          CORES: ${{ steps.cpu-cores.outputs.count }}
        run: |
          ./scripts/setup.sh

      - name: Generate stats
        run: |
          ./themes/projektemacher-base/scripts/stat.sh

      - name: Build Hugo site
        run: hugo --printI18nWarnings --printUnusedTemplates

      - name: Run post build script
        run: |
          ./scripts/post-build/qr-codes.sh

      - name: Validate JSON
        env:
          OSTYPE: linux
        run: |
          yarn run validate

      - name: Puppeteer
        run: ./themes/projektemacher-base/scripts/github/check-js-errors.sh

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
